version: '3.2'
services:
    api:
        build: ./kiln/api/.
        container_name: kiln_api
        restart: unless-stopped
        cgroup: host
        stop_grace_period: 10s
        stop_signal: SIGTERM
        privileged: true
        volumes:
            - ./data/kiln/packages:/kiln/packages
        environment:
            - kiln_DISABLE_NETWORKING=false
            - kiln_RUN_TIMEOUT=300000
            - kiln_REPO_URL=http://kiln_repo:8000/index
            - kiln_LOG_LEVEL=DEBUG
            - kiln_MAX_FILE_SIZE=500000000 # 500 MB
            - kiln_PROXY_DOMAIN=https://code-proxy.frohrer.com
        ports:
            - "2000:2000"
            - "2020:2020"
        networks:
            - kiln-network
    repo:
        build: ./kiln/repo/.
        container_name: kiln_repo
        privileged: true
        ports:
            - "8000:8000"
        networks:
            - kiln-network
        volumes:
            - kiln_repo_data:/app/packages
    ui:
        build: ./ui/
        container_name: kiln_ui
        environment:
            - API_BASE=http://kiln_api:2000/api/v2
        ports:
            - "8080:5000"
        networks:
            - kiln-network

networks:
    kiln-network:
        driver: bridge

volumes:
    kiln_repo_data:
