version: '3.2'
services:
    api:
        build: ./kiln/api/.
        container_name: kiln_api
        restart: unless-stopped
        cgroup: host
        stop_grace_period: 10s
        stop_signal: SIGTERM
        privileged: true
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            - PISTON_DISABLE_NETWORKING=false
            - PISTON_RUN_TIMEOUT=300000
            - PISTON_REPO_URL=http://piston_repo:8000/index
            - PISTON_LOG_LEVEL=DEBUG
            - PISTON_MAX_FILE_SIZE=500000000 # 500 MB
            - PISTON_PROXY_DOMAIN=https://code-proxy.frohrer.com
        ports:
            - "2000:2000"
            - "2020:2020"
        networks:
            - piston-network
    repo:
        build: ./kiln/repo/.
        container_name: piston_repo
        privileged: true
        ports:
            - "8000:8000"
        networks:
            - piston-network
        volumes:
            - piston_repo_data:/app/packages
    ui:
        build: ./ui/
        container_name: piston_ui
        environment:
            - API_BASE=http://piston_api:2000/api/v2
        ports:
            - "8080:5000"
        networks:
            - piston-network

networks:
    piston-network:
        driver: bridge

volumes:
    piston_repo_data:
