version: '3.2'

services:
    api:
        build: .
        container_name: piston_api_test
        restart: no
        privileged: true
        cgroup: host
        ports:
            - 2001:2000
            - 2020:2020
        environment:
            - PISTON_DISABLE_NETWORKING=${PISTON_DISABLE_NETWORKING}
            - PISTON_RUN_TIMEOUT=${PISTON_RUN_TIMEOUT}
            - PISTON_REPO_URL=${PISTON_REPO_URL}
            - PISTON_LOG_LEVEL=${PISTON_LOG_LEVEL}
            - PISTON_MAX_FILE_SIZE=${PISTON_MAX_FILE_SIZE}
        tmpfs:
            - /tmp:exec
